# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - blog.md
  - about.md
  - contact.md

footer: follow me on <a href="https://twitter.com/thenishagarwal/">twitter</a>

style: hacker

listen_for_clients_preferred_style: false

plugins:
  - jekyll-seo-tag

remote_theme: b2a3e8/jekyll-theme-console
