# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md
  - blog.md
footer: 'follow us on <a href="https://twitter.com/thenishagarwal/">twitter</a>'

style: hacker
listen_for_clients_preferred_style: false

plugins:
  - jekyll-seo-tag

theme: jekyll-theme-console
remote_theme: b2a3e8/jekyll-theme-console
